before_install:
- openssl aes-256-cbc -K $encrypted_4efdbe0d8830_key -iv $encrypted_4efdbe0d8830_iv
  -in cep-ninja-54574641e0d1.json.enc -out cep-ninja-54574641e0d1.json -d

language: node_js
node_js:
  - "12"

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: cep-ninja-54574641e0d1.json"
  project: cep-ninja
  on: master